"""empty message

Revision ID: a247c7af1b8f
Revises: 8ca3645f3321
Create Date: 2018-07-18 19:34:40.583198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a247c7af1b8f'
down_revision = '8ca3645f3321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('creat_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'creat_time')
    # ### end Alembic commands ###
